repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
        name: gitleaks

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python3.12)
        types: [python]
        language_version: python3.12
        args: ["--profile", "black"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        name: ruff (lint python3.12)
        types: [python]
        language_version: python3.12
        args: []

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black (python3.12)
        types: [python]
        args: [--line-length=120]
        language_version: python3.12

  - repo: https://github.com/asottile/dead
    rev: v2.1.0
    hooks:
      - id: dead
        name: dead (python3.12)
        types: [python]
        language_version: python3.12
        args: []

  - repo: https://github.com/dannysepler/rm_unneeded_f_str
    rev: v0.2.0
    hooks:
      - id: rm-unneeded-f-str
        name: rm-unneeded-f-str (python3.12)
        types: [python]
        language_version: python3.12
        args: []

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        name: mypy (python3.12)
        types: [python]
        language_version: python3.12
        args: ["--show-error-codes"]
