id: spotify-api-tracks-bigquery-daily
namespace: spotify-dwh-insights.ingestion

tasks:
  - id: elt_api_spotify_tracks
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
    containerImage: rj24/spotify-pipeline:v2.0
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: IF_NOT_PRESENT
      retry:
        maxAttempt: 3
        delay: PT5M  
      volumes:
        - /files:/key_gcp
    commands:
      #- python /app/spotify_data_pipeline.py --bucket_name={{ kv('BUCKET_NAME') }} --dataset_name={{ kv('DATASET_NAME') }}
      - --bucket_name={{ kv('BUCKET_NAME') }} --dataset_name={{ kv('DATASET_NAME') }}
    env:
      CLIENTE_ID: "{{ secret('CLIENTE_ID') }}"
      CLIENTE_SECRET: "{{ secret('CLIENTE_SECRET') }}"
      GOOGLE_APPLICATION_CREDENTIALS: gcp/gcs-storage-key.json

triggers:
    - id: schedule_daily_run
      type: io.kestra.plugin.core.trigger.Schedule
      cron: "0 6 * * *"