id: spotify-api-tracks-bigquery-daily
namespace: spotify-dwh-insights.ingestion

tasks:
  - id: elt_api_spotify_tracks
    type: io.kestra.plugin.scripts.python.Commands
    retry:
      maxAttempt: 3
      interval: PT5M
      type: constant
    namespaceFiles:
      enabled: true
    inputFiles:
      sa.json: "{{ secret('GCP_CREDENTIALS') }}"
    containerImage: rj24/spotify-pipeline:v3.0
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: ALWAYS
    commands:
      - python /app/spotify_data_pipeline.py --bucket_name={{ kv('BUCKET_NAME') }} --dataset_name={{ kv('DATASET_NAME') }}
    env:
      CLIENTE_ID: "{{ secret('CLIENTE_ID') }}"
      CLIENTE_SECRET: "{{ secret('CLIENTE_SECRET') }}"
      GOOGLE_APPLICATION_CREDENTIALS: sa.json

triggers:
  - id: twice_daily_run
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 6,18 * * *"
    timezone: "America/Asuncion"
