FROM python:3.13-slim

WORKDIR /app
COPY spotify_data_pipeline.py .

RUN pip install --no-cache-dir \
    requests requests-cache pandas pyarrow \
    google-cloud-storage google-cloud-bigquery-storage \
    dlt[bigquery]

ENTRYPOINT ["python", "spotify_data_pipeline.py"]
