FROM python:3.12

RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY spotify_data_pipeline.py .

RUN pip install --no-cache-dir requests requests-cache pandas pyarrow google-cloud-storage google-cloud-bigquery-storage dlt[bigquery]

ENTRYPOINT ["python", "spotify_data_pipeline.py"]