name: Deploy Kestra Flows
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'kestra/flows/**'

jobs:
  validate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Kestra validate flows
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Validate all flows
        uses: kestra-io/validate-action@master
        with:
          directory: ./kestra/flows
          resource: flow
          server: http://${{secrets.KESTRA_HOSTNAME}}:8080
          user: ${{secrets.KESTRA_USER}}
          password: ${{secrets.KESTRA_PASSWORD}}

  prod:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Deploy flows to prod
    needs: validate
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Deploy spotify-dwh-insights.prod flows
        uses: kestra-io/deploy-action@master
        with:
          namespace: spotify-dwh-insights.prod
          directory: ./kestra/flows/spotify-dwh-insights/prod
          resource: flow
          server: http://${{secrets.KESTRA_HOSTNAME}}:8080
          user: ${{secrets.KESTRA_USER}}
          password: ${{secrets.KESTRA_PASSWORD}}
          delete: false

      - name: Deploy spotify-dwh-insights.ingestion flows
        uses: kestra-io/deploy-action@master
        with:
          namespace: spotify-dwh-insights.ingestion
          directory: ./kestra/flows/spotify-dwh-insights/ingestion
          resource: flow
          server: http://${{secrets.KESTRA_HOSTNAME}}:8080
          user: ${{secrets.KESTRA_USER}}
          password: ${{secrets.KESTRA_PASSWORD}}
          delete: false

      - name: Deploy spotify-dwh-insights.transformation flows
        uses: kestra-io/deploy-action@master
        with:
          namespace: spotify-dwh-insights.transformation
          directory: ./kestra/flows/spotify-dwh-insights/transformation
          resource: flow
          server: http://${{secrets.KESTRA_HOSTNAME}}:8080
          user: ${{secrets.KESTRA_USER}}
          password: ${{secrets.KESTRA_PASSWORD}}
          delete: false
  
  run-init-kv:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Run init-prod-kv flow
    needs: prod 
    steps:
      - name: Wait for Kestra to be healthy
        run: |
          echo "Esperando a que Kestra esté arriba..."
          for i in {1..10}; do
            if curl -s -u "${{ secrets.KESTRA_USER }}:${{ secrets.KESTRA_PASSWORD }}" http://${{ secrets.KESTRA_HOSTNAME }}:8081/health | grep '"status":"UP"' > /dev/null; then
              echo "Kestra está listo."
              break
            else
              echo "Esperando 10 segundos..."
              sleep 10
            fi
          done

      - name: Run init-prod-kv flow
        run: |
          echo "Lanzando el flujo init-prod-kv..."
          curl -v -X POST "http://${{ secrets.KESTRA_HOSTNAME }}:8080/api/v1/executions/spotify-dwh-insights.prod/init-prod-kv" \
            -u "${{ secrets.KESTRA_USER }}:${{ secrets.KESTRA_PASSWORD }}" \
            -H "Content-Type: multipart/form-data"
