name: Infra Provision

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Terraform workflow
    defaults:
      run:
        working-directory: terraform
    env:
      TF_VAR_kestra_user: ${{ secrets.KESTRA_USER }}
      TF_VAR_kestra_password: ${{ secrets.KESTRA_PASSWORD }}
      TF_VAR_postgres_db: ${{ secrets.POSTGRES_DB }}
      TF_VAR_postgres_user: ${{ secrets.POSTGRES_USER }}
      TF_VAR_postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
      TF_VAR_secret_cliente_id: ${{ secrets.SECRET_CLIENTE_ID_BASE64 }}
      TF_VAR_secret_cliente_secret: ${{ secrets.SECRET_CLIENTE_SECRET_BASE64 }}
      TF_VAR_secret_project_id: ${{ secrets.SECRET_PROJECT_ID_BASE64 }}
      TF_VAR_secret_gcp_credentials: ${{ secrets.SECRET_GCP_CREDENTIALS_BASE64 }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_JSON }}'

      - name: Verify gcloud auth
        run: gcloud auth list

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
