name: CI-CD-Deploy-Kestra-Instance
on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'kestra/docker-compose.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Set up SSH key for GCP
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{secrets.GCP_PROJECT_ID}}

      - name: Copy docker-compose.yaml to GCP instance
        run: |
          gcloud compute scp ./kestra/docker-compose.yaml ${{secrets.GCP_INSTANCE_NAME}}:/home/docker-compose.yaml --zone ${{secrets.GCP_ZONE}} --project ${{secrets.GCP_PROJECT_ID}}
          gcloud compute ssh ${{secrets.GCP_INSTANCE_NAME}} --zone ${{secrets.GCP_ZONE}} --project ${{secrets.GCP_PROJECT_ID}} --command "sudo mv /home/docker-compose.yaml /opt/kestra/docker-compose.yaml"

      - name: Restart Docker Compose on GCP instance
        run: |
          gcloud compute ssh ${{secrets.GCP_INSTANCE_NAME}} --zone ${{secrets.GCP_ZONE}} --project ${{secrets.GCP_PROJECT_ID}} --command "
            cd /opt/kestra &&
            docker-compose down &&
            docker-compose pull &&
            docker-compose up -d
          "
