name: CI-CD-Build-Deploy-Docker-Image

on:
  push:
    branches:
        - 'develop'
    paths:
      - 'dlt/dockerfile'
      - 'dlt/spotify_data_pipeline.py'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push Docker image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          # Define the version tags
          VERSION=$(date +'%Y%m%d')
          IMAGE_NAME=rj24/spotify-pipeline

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

          # Build the Docker image
          cd ./dlt
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:v$VERSION .

      - name: Push Docker image to DockerHub
        run: |
          # Push both tags to DockerHub
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:v$VERSION
